### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by ingbrzy** [lord-ralf-adolf/Lordroid_One_Deodexer_To_Rule_Them_ALL#11]
when using command line in 1.27 it always zipalign apks.. even no "z" parameter...

btw. how to set 4 threads using command line..?

**Comment by lord-ralf-adolf** [comment]
launch the gui tool and change the max jobs from file > settings > performance  ,by default it will use your number of available cpus

**Comment by ingbrzy** [comment]
Thank you... 

I am using your tool on the server so ssh access only... so cant set cpus via GUI... any way how to set it in settings file manually..? will it be used in command line task..?

**Comment by lord-ralf-adolf** [comment]
yes in the file app_config.rsx (text file with UTF-8 encoding)
change the value of this proprety don't go higher than 4 
`max.job.prop=4`

**Comment by ingbrzy** [comment]
Changed max.job.prop=4 but it always use just one core for deodexing via command line...

**Comment by lord-ralf-adolf** [comment]
oh yes , fixed in the latest commit https://github.com/lord-ralf-adolf/Lordroid_One_Deodexer_To_Rule_Them_ALL/commit/4a2f2454f1c836d4e3cd9cf00ad4dcb23f6b470b
try building against latest master

**Comment by ingbrzy** [comment]
@lord-ralf-adolf awesome! now its a beast! thank you!
